filepath = '.venv/foreign_price_scraper_dual.py'

with open(filepath, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Keep everything before def main() by dynamically locating it
main_start_idx = None
for idx, line in enumerate(lines):
    if line.strip().startswith("def main():"):
        main_start_idx = idx
        break

if main_start_idx is None:
    raise Exception("Could not find def main() in the file")

header = lines[:main_start_idx]

new_main = (
    "\n"
    "def main():\n"
    "    parser = argparse.ArgumentParser(description=\"Dual-browser Scraper for Палета 1 - Іноземні\")\n"
    "    parser.add_argument(\"--start-row\", type=int, default=2, help=\"Start row (default: 2)\")\n"
    "    parser.add_argument(\"--end-row\", type=int, default=None, help=\"End row (default: last)\")\n"
    "    parser.add_argument(\"--mode\", type=str, default=\"A\", choices=[\"A\", \"S\"],\n"
    "                        help=\"A=Auto, S=Step-by-step (waits for confirmation each book)\")\n"
    "    parser.add_argument(\"--headless\", action=\"store_true\", help=\"Run browsers in headless (text) mode\")\n"
    "    args = parser.parse_args()\n"
    "\n"
    "    # Enforce UTF-8 for output streams to prevent corrupted emoji/characters in log files and console\n"
    "    import sys\n"
    "    if sys.stdout.encoding != 'utf-8':\n"
    "        try:\n"
    "            sys.stdout.reconfigure(encoding='utf-8')\n"
    "        except AttributeError:\n"
    "            pass\n"
    "    if sys.stderr.encoding != 'utf-8':\n"
    "        try:\n"
    "            sys.stderr.reconfigure(encoding='utf-8')\n"
    "        except AttributeError:\n"
    "            pass\n"
    "\n"
    "    def update_live_report(row_num, title, matches):\n"
    "        md_file = \"successful_searches.md\"\n"
    "        existing_matches = []\n"
    "        def clean_str(val):\n"
    "            if not isinstance(val, str):\n"
    "                return val\n"
    "            return \"\".join(c for c in val if not (0xD800 <= ord(c) <= 0xDFFF))\n"
    "        title = clean_str(title)\n"
    "        cleaned_matches = []\n"
    "        for m in matches:\n"
    "            cleaned_matches.append({\n"
    "                'site': clean_str(m.get('site', '')),\n"
    "                'price': clean_str(m.get('price', '')),\n"
    "                'url': clean_str(m.get('url', '')),\n"
    "                'formula': clean_str(m.get('formula', ''))\n"
    "            })\n"
    "        matches = cleaned_matches\n"
    "        if os.path.exists(md_file):\n"
    "            try:\n"
    "                with open(md_file, \"r\", encoding=\"utf-8\") as f:\n"
    "                    lines = f.readlines()\n"
    "                table_started = False\n"
    "                for line in lines:\n"
    "                    if \"| Row\" in line or \"| Рядок\" in line or \"|---\" in line:\n"
    "                        table_started = True\n"
    "                        continue\n"
    "                    if table_started and line.strip().startswith(\"|\"):\n"
    "                        parts = [p.strip() for p in line.split(\"|\")[1:-1]]\n"
    "                        if len(parts) >= 6:\n"
    "                            try:\n"
    "                                clean_row = parts[0].replace(\"**\", \"\").strip()\n"
    "                                r = int(clean_row)\n"
    "                                t = clean_str(parts[1].replace(\"\\\\|\", \"|\").strip())\n"
    "                                s = clean_str(parts[2].replace(\"`\", \"\").strip())\n"
    "                                p = clean_str(parts[3].replace(\"`\", \"\").strip())\n"
    "                                u_match = re.search(r'\\[.*?\\]\\((.*?)\\)', parts[5])\n"
    "                                u = clean_str(u_match.group(1) if u_match else parts[5].strip())\n"
    "                                d = clean_str(parts[6].strip())\n"
    "                                existing_matches.append({\n"
    "                                    'row': r, 'title': t, 'site': s, 'price': p, 'url': u, 'date': d\n"
    "                                })\n"
    "                            except:\n"
    "                                pass\n"
    "            except Exception as e:\n"
    "                log_message(f\"\\u26a0\\ufe0f Помилка читання існуючого звіту: {e}\")\n"
    "        \n"
    "        now_str = datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n"
    "        for m in matches:\n"
    "            duplicate = False\n"
    "            for ex in existing_matches:\n"
    "                if ex['row'] == row_num and ex['site'] == m['site'] and ex['price'] == m['price']:\n"
    "                    duplicate = True\n"
    "                    break\n"
    "            if not duplicate:\n"
    "                existing_matches.append({\n"
    "                    'row': row_num,\n"
    "                    'title': title,\n"
    "                    'site': m['site'],\n"
    "                    'price': m['price'],\n"
    "                    'url': m['url'],\n"
    "                    'date': now_str\n"
    "                })\n"
    "        \n"
    "        existing_matches.sort(key=lambda x: (x['row'], x['site']))\n"
    "        total_found = len(set(x['row'] for x in existing_matches))\n"
    "        site_counts = {}\n"
    "        for ex in existing_matches:\n"
    "            site_counts[ex['site']] = site_counts.get(ex['site'], 0) + 1\n"
    "        \n"
    "        ebay_count = site_counts.get('ebay.com', 0)\n"
    "        amazon_count = site_counts.get('amazon.com', 0)\n"
    "        abebooks_count = site_counts.get('abebooks.com', 0)\n"
    "        biblio_count = site_counts.get('biblio.com', 0)\n"
    "        \n"
    "        try:\n"
    "            with open(md_file, \"w\", encoding=\"utf-8\") as f:\n"
    "                f.write(\"# \\U0001f4da Автономний пошук книг - Живий звіт\\n\\n\")\n"
    "                f.write(\"> [!NOTE]\\n\")\n"
    "                f.write(\"> Цей звіт оновлюється в **режимі реального часу** автономним скрапером. Він об'єднує результати всіх запусків, щоб показати повну історію знайдених цін на книги.\\n\\n\")\n"
    "                f.write(\"## \\U0001f4ca Панель стану скрапера\\n\")\n"
    "                f.write(f\"- **Останнє оновлення:** `{now_str}`\\n\")\n"
    "                f.write(f\"- **Всього знайдено унікальних книг:** `{total_found}`\\n\")\n"
    "                f.write(\"- **Розподіл знайдених цін по сайтах:**\\n\")\n"
    "                f.write(f\"  - \\U0001f6cd\\ufe0f **eBay:** `{ebay_count}` збігів\\n\")\n"
    "                f.write(f\"  - \\U0001f4e6 **Amazon:** `{amazon_count}` збігів\\n\")\n"
    "                f.write(f\"  - \\U0001f4d6 **AbeBooks:** `{abebooks_count}` збігів\\n\")\n"
    "                f.write(f\"  - \\U0001f4da **Biblio:** `{biblio_count}` збігів\\n\\n\")\n"
    "                f.write(\"---\\n\\n\")\n"
    "                f.write(\"## \\U0001f4c8 Історія успішних пошуків\\n\")\n"
    "                f.write(\"| Рядок | Назва книги | Сайт | Початкова ціна | Формула | Джерело | Знайдено о |\\n\")\n"
    "                f.write(\"|:---:|---|:---:|:---:|:---:|:---:|:---:|\\n\")\n"
    "                for ex in existing_matches:\n"
    "                    clean_t = ex['title'].replace(\"|\", \"\\\\|\")\n"
    "                    pr = ex['price']\n"
    "                    if not pr.startswith(\"$\") and not pr.startswith(\"\\u20ac\") and not pr.startswith(\"\\u00a3\"):\n"
    "                        if pr and (pr[0].isdigit() or pr[0] == '.'):\n"
    "                            pr = f\"${pr}\"\n"
    "                    raw_numeric = re.sub(r'[^\\d.]', '', ex['price'])\n"
    "                    formula = f\"`={raw_numeric}*CURRENCY`\" if raw_numeric else \"Недоступно\"\n"
    "                    f.write(f\"| **{ex['row']}** | {clean_t} | `{ex['site']}` | `{pr}` | {formula} | [Посилання]({ex['url']}) | {ex['date']} |\\n\")\n"
    "            log_message(f\"\\U0001f4dd Звіт {md_file} успішно оновлено конструктивно.\")\n"
    "        except Exception as e:\n"
    "            log_message(f\"\\u26a0\\ufe0f Не вдалося записати звіт у файл: {e}\")\n"
    "\n"
    "    init_google_clients()\n"
    "\n"
    "    all_data = worksheet.get_all_values()\n"
    "    total_rows = len(all_data)\n"
    "    log_message(f\"\\U0001f4ca Зчитано таблицю: {total_rows} рядків (включаючи заголовок).\")\n"
    "\n"
    "    end_row = args.end_row if args.end_row else total_rows\n"
    "    start_row = args.start_row\n"
    "\n"
    "    if args.mode == \"S\":\n"
    "        log_message(\"\\U0001f535 Режим: НАПІВАВТОМАТИЧНИЙ — очікування підтвердження перед кожною книгою.\")\n"
    "    else:\n"
    "        log_message(\"\\U0001f7e2 Режим: АВТОМАТИЧНИЙ.\")\n"
    "\n"
    "    success_count = 0\n"
    "    failure_count = 0\n"
    "    skipped_count = 0\n"
    "    found_books = []\n"
    "\n"
    "    driver_store = init_driver(instance_id=0, headless=args.headless)\n"
    "    driver_search = init_driver(instance_id=1, headless=args.headless)\n"
    "\n"
    "    try:\n"
    "        log_message(\"Відвідуємо сайти для прогріву...\")\n"
    "        driver_store.get(\"https://www.ebay.com\")\n"
    "        time.sleep(2)\n"
    "        driver_store.get(\"https://www.abebooks.com\")\n"
    "        time.sleep(2)\n"
    "        driver_search.get(\"https://www.google.com\")\n"
    "        time.sleep(2)\n"
    "\n"
    "        for i in range(start_row, end_row + 1):\n"
    "            if i > len(all_data):\n"
    "                break\n"
    "\n"
    "            row_data = all_data[i - 1]\n"
    "            col_indices = [5, 6, 7]  # F, G, H\n"
    "            col_chars = {5: 'F', 6: 'G', 7: 'H'}\n"
    "            empty_cols = []\n"
    "\n"
    "            for c_idx in col_indices:\n"
    "                val = row_data[c_idx].strip() if len(row_data) > c_idx else \"\"\n"
    "                if not val:\n"
    "                    empty_cols.append(c_idx)\n"
    "\n"
    "            if not empty_cols:\n"
    "                log_message(f\"\\u23e9 Рядок {i}: Всі три ціни вже знайдено. Пропуск.\")\n"
    "                skipped_count += 1\n"
    "                continue\n"
    "\n"
    "            if len(row_data) < 3 or not row_data[2].strip():\n"
    "                log_message(f\"\\u23e9 Рядок {i}: Назва книги відсутня. Пропуск.\")\n"
    "                skipped_count += 1\n"
    "                continue\n"
    "\n"
    "            title = row_data[2].strip()\n"
    "            col_d = row_data[3].strip() if len(row_data) > 3 else \"\"\n"
    "\n"
    "            log_message(f\"\\n==================================================\")\n"
    "            log_message(f\"\\U0001f4d8 [Рядок {i}] Назва: {title}\")\n"
    "            log_message(f\"\\U0001f4c5 Рік: {col_d}\")\n"
    "            log_message(f\"\\u23f3 Потрібно заповнити стовпці: {[col_chars[c] for c in empty_cols]}\")\n"
    "            log_message(f\"==================================================\")\n"
    "\n"
    "            # STEP-BY-STEP: confirmation BEFORE search\n"
    "            if args.mode == \"S\":\n"
    "                print(f\"\\n\\u25b6  РЯДОК {i}\")\n"
    "                print(f\"   Книга : {title}\")\n"
    "                print(f\"   Рік   : {col_d}\")\n"
    "                print(f\"   [Enter] — шукати  |  s — пропустити  |  q — вийти\")\n"
    "                user_input = input(\">> \").strip().lower()\n"
    "                if user_input == \"q\":\n"
    "                    log_message(\"\\U0001f44b Вихід за командою користувача.\")\n"
    "                    break\n"
    "                elif user_input == \"s\":\n"
    "                    log_message(f\"\\u23e9 Рядок {i}: Пропущено за командою користувача.\")\n"
    "                    skipped_count += 1\n"
    "                    continue\n"
    "\n"
    "            search_sites = get_search_sites_by_year(row_data)\n"
    "            matches = []\n"
    "\n"
    "            for site in search_sites:\n"
    "                if len(matches) >= len(empty_cols):\n"
    "                    break\n"
    "                log_message(f\"\\U0001f50e Пошук на сайті {site}...\")\n"
    "                try:\n"
    "                    url, resolved_title = find_link_parallel(driver_store, driver_search, site, title)\n"
    "                    if url:\n"
    "                        col_char = col_chars[empty_cols[len(matches)]]\n"
    "                        formula, price = process_product_page(driver_store, url, site, i, col_char, resolved_title)\n"
    "                        if formula:\n"
    "                            matches.append({'site': site, 'price': price, 'formula': formula, 'url': url})\n"
    "                            log_message(f\"\\u2705 Знайдено ціну на {site}: {price}\")\n"
    "                    else:\n"
    "                        log_message(f\"\\u274c Не знайдено книги на {site}\")\n"
    "                except Exception as err:\n"
    "                    log_message(f\"\\u26a0\\ufe0f Помилка пошуку на {site}: {err}\")\n"
    "\n"
    "            if matches:\n"
    "                updates = []\n"
    "                notes_to_update = []\n"
    "                for idx, match in enumerate(matches):\n"
    "                    target_c_idx = empty_cols[idx]\n"
    "                    char = col_chars[target_c_idx]\n"
    "                    updates.append({'range': f\"{char}{i}\", 'values': [[match['formula']]]})\n"
    "                    notes_to_update.append((char, match['url']))\n"
    "\n"
    "                # STEP-BY-STEP: confirmation BEFORE saving\n"
    "                if args.mode == \"S\":\n"
    "                    print(f\"\\n\\u2705 ЗНАЙДЕНО {len(matches)} ціни:\")\n"
    "                    for m in matches:\n"
    "                        print(f\"   \\U0001f4b0 {m['site']}: {m['price']}\")\n"
    "                        print(f\"   \\U0001f517 {m['url'][:90]}\")\n"
    "                    print(f\"   [Enter] — зберегти в таблицю  |  s — не зберігати  |  q — вийти\")\n"
    "                    confirm = input(\">> \").strip().lower()\n"
    "                    if confirm == \"q\":\n"
    "                        log_message(\"\\U0001f44b Вихід за командою користувача.\")\n"
    "                        break\n"
    "                    elif confirm == \"s\":\n"
    "                        log_message(f\"\\u23e9 Рядок {i}: Збереження скасовано.\")\n"
    "                        skipped_count += 1\n"
    "                        time.sleep(random.uniform(2, 4))\n"
    "                        continue\n"
    "\n"
    "                try:\n"
    "                    worksheet.batch_update(updates, value_input_option='USER_ENTERED')\n"
    "                    for char, url in notes_to_update:\n"
    "                        try:\n"
    "                            worksheet.update_note(f\"{char}{i}\", f\"Джерело: {url}\")\n"
    "                        except:\n"
    "                            pass\n"
    "                    log_message(f\"\\U0001f3af Рядок {i} оновлено успішно!\")\n"
    "                    success_count += 1\n"
    "                    found_books.append((i, title, matches))\n"
    "                    # Real-time local markdown update\n"
    "                    update_live_report(i, title, matches)\n"
    "                except Exception as e:\n"
    "                    log_message(f\"\\u274c Не вдалося записати в таблицю: {e}\")\n"
    "            else:\n"
    "                log_message(f\"\\u26a0\\ufe0f Жодних цін не знайдено для рядка {i}.\")\n"
    "                failure_count += 1\n"
    "\n"
    "            time.sleep(random.uniform(2, 4))\n"
    "            log_message(f\"\\U0001f4c8 [ПРОГРЕС] Рядок {i}/{end_row} оброблено | Знайдено: {success_count} | Без результатів: {failure_count} | Пропущено: {skipped_count}\")\n"
    "\n"
    "        log_message(\"\\n==================================================\")\n"
    "        log_message(\"\\U0001f4ca ПІДСУМОК РОБОТИ СКРАПЕРА:\")\n"
    "        log_message(\"==================================================\")\n"
    "        log_message(f\"\\u2705 Успішно знайдено та оновлено в таблиці: {success_count} книг\")\n"
    "        log_message(f\"\\u274c Не знайдено цін для: {failure_count} книг\")\n"
    "        log_message(f\"\\u23e9 Пропущено рядків: {skipped_count}\")\n"
    "        if found_books:\n"
    "            log_message(\"\\n\\u2728 Деталі успішних пошуків:\")\n"
    "            for row_num, t, matches in found_books:\n"
    "                log_message(f\"   \\U0001f4d8 [Рядок {row_num}] {t}\")\n"
    "                for m in matches:\n"
    "                    log_message(f\"      \\U0001f4b0 {m['site']}: {m['price']} -> {m['url']}\")\n"
    "        log_message(\"==================================================\")\n"
    "\n"
    "    except KeyboardInterrupt:\n"
    "        log_message(\"\\U0001f44b Перервано користувачем (Ctrl+C).\")\n"
    "    finally:\n"
    "        try:\n"
    "            driver_store.quit()\n"
    "        except:\n"
    "            pass\n"
    "        try:\n"
    "            driver_search.quit()\n"
    "        except:\n"
    "            pass\n"
    "\n"
    "\n"
    "if __name__ == \"__main__\":\n"
    "    main()\n"
)

with open(filepath, 'w', encoding='utf-8') as f:
    f.writelines(header)
    f.write(new_main)

with open(filepath, 'r', encoding='utf-8') as f:
    result = f.readlines()
print(f"Done. Total lines: {len(result)}")
